### ISSUE TITLE
project under windows

### ISSUE THREAD

**Issue by filipdns** [iotbzh/qml_radio_plugin#1]
Hello sir,

I would like to bouild this project under windows / VS2015 but I think Alsa is only on linux, can I turn your project to Win? If yes how?

Kind regards
Philippe

**Comment by kooltux** [comment]
I think this will be difficult to port as is because there are a few dependencies you won't solve under windows. You may have more chance with the upstream project rtl-sdr. Did you check https://osmocom.org/projects/rtl-sdr/wiki ?

**Comment by kooltux** [comment]
This project is inactive.
