### ISSUE TITLE
This project is alive right now?

### ISSUE THREAD

**Issue by EmadDeve20** [iotbzh/qml_radio_plugin#2]
hello i trying to use this program built in installation i got an error:

```
./configure
...

configure: error: Package requirements (alsa) were not met:

No package 'alsa' found
```

but i have alsa
```
sudo apt install alsa
```

if i write command alsa in my terminal i get output like this:
```
Usage: /sbin/alsa {unload|reload|force-unload|force-reload|suspend|resume}
```

so for this i think your program need an update!

**Comment by kooltux** [comment]
Hi,
No this project is not active anymore. But feel free to fork it and restart it!
